### ISSUE TITLE
Reaper scales layout every time it's recreated

### ISSUE THREAD

**Issue by nezvers** [iPlug2/iPlug2OOS#10]
Windows 10 VST3
Reproduction steps:
- build template 
- launch debug with Reaper
- add extra plugin to change drawn plugin
- select IPlugTemplate (it's getting bigger every time it's redrawn)

Doesn't happen with iPlug2 examples.

**Comment by olilarkin** [comment]
what platform/format?

**Comment by nezvers** [comment]
Updated

**Comment by olilarkin** [comment]
thanks. I believe this is fixed by applying the changes on this branch https://github.com/iPlug2/iPlug2/tree/VST3/screen-scaled to the iPlug2 submodule

the issue is tracked here: https://github.com/iPlug2/iPlug2/issues/740 , so i will close this issue since it is an iPlug2 issue not iPlug2OOS
