### ISSUE TITLE
[QUESTION] Recommended way to rename "TemplateProject"

### ISSUE THREAD

**Issue by sdatkinson** [iPlug2/iPlug2OOS#5]
Hi, Oli!

Question: is there an "easy" way that you'd recommend renaming everything in this repo that's called "TemplateProject" with something that I pick for my own project?  I can think of doing a humongous find-and-replace, but I suspect there's something more clever that you intend to be done?

Thanks in advance!

**Comment by olilarkin** [comment]
The duplicate.py script is there for exactly that purpose. :-)

**Comment by sdatkinson** [comment]
Ah, there it is. I knew I was missing something obvious 🙂

Thanks!
